version: "3.7"
services:
  photo-stream:
    container_name: photo-stream
    image: waschinski/photo-stream:latest
    #To build from source, comment previous line and uncomment next line
    #build: .
    environment:
      - TITLE=maxvoltar.photo
      - EMAIL=tim@maxvoltar.be
      - AUTHOR_NAME=Tim Van Damme
      - AUTHOR_EMAIL=tim@maxvoltar.be
      - AUTHOR_WEBSITE=https://maxvoltar.com
      - DESCRIPTION=@maxvoltar's minimalistic, self-hosted photo stream.
      - BASEURL=
      - URL=https://maxvoltar.photo/
      - SHOW_OFFICIAL_GITHUB=1
    volumes:
      - photos:/photo-stream/photos
    ports:
      - "4000:4000"
    restart: unless-stopped
volumes:
  photos:
